### ISSUE TITLE
Week 4 Project 1 Audio files not working on gh-pages

### ISSUE THREAD

**Issue by MeredithS** [MeredithS/Simonsays#3]
Hi Phil!

I pushed up my game to gh-pages but my audio files won't work!  The audio files work on the master branch but not the gh-pages branch.  My audio files were saved in a file called Audio that were pushed up to the gh-pages branch. I got an error message of:

Failed to load resource: the server responded with a status of 404 (Not Found)    http://merediths.github.io/Simonsays/audio/redColor_tone.mov 

this message pops up for each of my sounds.

I moved all my audio files out of the Audio directory and into the main simonsays directory hoping that would help solve the issue but now I am getting this response:

GET http://merediths.github.io/Simonsays/audio/redColor_tone.mov
merediths.github.io/

Please help!

**Comment by phlco** [comment]
Your index file is still sourcing them from `"src="audio/yellowColor_tone.mov"`

I don't see an audio folder. Gotta match it up!
